# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check_formatting:
    # This job is to check the formatting of files
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      # Clone the repository
      - uses: actions/checkout@v2

      # Install elm-format
      - name: Install elm-format
        uses: mpizenberg/elm-tooling-action@v1.2
        with:
          cache-key: elm-home-${{ hashFiles('elm-tooling.json', 'elm.json') }}
          cache-restore-key: elm-home

      - name: Check formatting
        run: npm run format
